[build]
  base = ""
  command = "pnpm build:h5"
  publish = "packages/h5/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 